apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-app-0418 
  janus-idp.io/tekton: py-app-0418
  backstage.io/kubernetes-id: py-app-0418
  backstage.io/kubernetes-namespace: py-app-0418 
  app.kubernetes.io/part-of: py-app-0418
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  