apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: py-app-0418
  janus-idp.io/tekton: py-app-0418
  backstage.io/kubernetes-id: py-app-0418
  backstage.io/kubernetes-namespace: py-app-0418 
  app.kubernetes.io/part-of: py-app-0418
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
