apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-app-0418
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-app-0418 
  name: py-app-0418
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-app-0418 
